// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type User struct {
	ID           int32
	Username     string
	Password     string
	RefreshToken sql.NullString
}
