version: "3.8"

name: "words-reminder-api"

services:
  db:
    image: "mysql:8.1.0"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=thisisverysecret
      - MYSQL_DATABASE=words_reminder